<?xml version="1.0" encoding="UTF-8"?>
<!-- digdown is a third-party PaperMC plugin for Minecraft Java Edition -->
<!-- that forces the warden to tick even in non-simulated chunks. -->

<!-- Copyright (C) 2026 VidTu -->

<!-- This program is free software: you can redistribute it and/or modify -->
<!-- it under the terms of the GNU General Public License as published by -->
<!-- the Free Software Foundation, either version 3 of the License, or -->
<!-- (at your option) any later version. -->

<!-- This program is distributed in the hope that it will be useful, -->
<!-- but WITHOUT ANY WARRANTY; without even the implied warranty of -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the -->
<!-- GNU General Public License for more details. -->

<!-- You should have received a copy of the GNU General Public License -->
<!-- along with this program.  If not, see <https://www.gnu.org/licenses/>. -->

<!-- SPDX-License-Identifier: GPL-3.0-or-later -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>ru.vidtu.digdown</groupId>
    <artifactId>digdown</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>digdown</name>
    <description>Force the warden to tick even in non-simulated chunks.</description>
    <url>https://github.com/VidTu/digdown</url>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>25</maven.compiler.release>
        <file.encoding>UTF-8</file.encoding>
        <user.language>en</user.language>
        <user.country>US</user.country>
        <user.variant/>
        <project.build.outputTimestamp>1980-01-01T00:00:02Z</project.build.outputTimestamp>
    </properties>
    <repositories>
        <repository>
            <id>papermc</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>26.2.build.112-stable</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
</project>
